[build]
target = "x86_64-unknown-none"

[unstable]
build-std-features = ["compiler-builtins-mem", "slice_pattern"]
build-std = ["core", "compiler_builtins", "alloc"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
