[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
# bootloader = { version = "0.9.8", features = ["map_physical_memory"]}
bootloader_api = { version = "0.11.0" }
kernel_vga_buffer = { path = "kernel_vga_buffer" }
volatile = "0.4.5"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = { version = "0.9.4" }
uart_16550 = "0.2.0"
pal = { path = "pal" }


[target.'cfg(target_arch = "x86_64")'.dependencies]
pal_x86_64 = { path = "pal_x86_64" }

[package.metadata.bootimage]
build-command = ["build"]
run-command = ["qemu-system-x86_64", "-drive", "format=raw,file={}"]
run-args = []
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", "-display", "none"]
test-success-exit-code = 3
test-timeout = 300
test-no-reboot = true